pericentre = 8.656410725524182
apocentre = 102.27814867329506
pericentres = [10.95775080372714, 9.070274923622474, 8.656410725524182, 3.4858498875637505, 4.108835401238604, 10.209994122887744, 15.447539397132518]
apocentres = [102.65130665018455, 102.27814867329506, 102.35240801068048, 100.27886155432488, 95.85268273100634, 88.42660234288797, 77.98661614141554]
period = 1.3242116638183594
idx_peris = [17, 45, 73, 101, 129, 157, 186]
idx_apos = [31, 59, 87, 115, 143, 171, 199]
t_peris = [159.931640625, 439.94140625, 719.951171875, 999.9609375, 1279.970703125, 1559.98046875, 1850.0830078125]
t_apos = [299.9365234375, 579.9462890625, 859.9560546875, 1139.9658203125, 1419.9755859375, 1699.9853515625, 1979.9951171875]
idx_f = 76
idx_peri = 73
t_last_peri = 0.14154208984375005
t_f_gyr = 3.536111865234375
ra_f = 210.1258727471549
dec_f = 27.917529023400046
distance_f = 48.99702222946022
pmra_f = -1.1334488515788523
pmdec_f = -0.8509358221620208
radial_velocity_f = -0.8509358221620208
theta0 = -101.50375051473021
chi2_best = 10.841378050247535
chi2_best_interp = 10.841378050247535
