pericentre = 10.144114953622855
apocentre = 112.53945287846541
n_peris = 4
time_last_peri = -27.9628724963361
Lx_f = 21.904939198628426
Ly_f = -5.853349081231585
Lz_f = 0.06825173828485731
E_f = -1.395921285776002
period = -315.3590620420127
period_apo = -315.3590620420127
dt = -529.9999999999999
peri_apo_max_err = 0.07339521371788926
x_i = -4.277642250061035
y_i = -14.757668495178223
z_i = 111.48561096191406
v_x_i = -0.051322631537914276
v_y_i = -0.1930161863565445
v_z_i = -0.025862006470561028
ra = 209.3
dec = 26.8
distance = 47.1
pmra = -1.25
pmdec = -0.93
radial_velocity = 196.9
x = 1.7017489739408365
y = 6.899745208079477
z = 45.565261742882946
v_x = -16.780736791036837
v_y = -59.71937955173533
v_z = 264.06124246969483
orbit_name = "largeperi"
idx_i = 471
t_i = -816.619443087445
ra_err = 0.0
dec_err = 0.0
distance_err = 0.43080150822559915
pmra_err = 0.037
pmdec_err = 0.035
radial_velocity_err = 3.8
