pericentre = 10.906568814963805
apocentre = 105.57688974142967
pericentres = [10.98541344095366, 13.708866438333267, 10.906568814963805, 11.860933880163241]
apocentres = [106.87008214174546, 105.57688974142967, 104.81497766833733]
period = 1.376862880859375
idx_peris = [17, 46, 76, 105]
idx_apos = [32, 61, 90]
t_peris = [159.931640625, 450.0341796875, 749.970703125, 1040.0732421875]
t_apos = [310.029296875, 599.873046875, 889.9755859375]
idx_f = 79
idx_peri = 76
t_last_peri = 0.14154208984375005
t_f_gyr = 3.677653955078125
ra_f = 207.37741777072617
dec_f = 26.804546945716297
distance_f = 52.027462844733826
pmra_f = -1.037832721447157
pmdec_f = -0.8368678385618531
radial_velocity_f = -0.8368678385618531
theta0 = -104.56840377240293
chi2_best = 33.447412648327614
chi2_best_interp = 33.447412648327614
