pericentre = 6.985281688873827
apocentre = 104.10582888974795
n_peris = 4
time_last_peri = -27.44504152418173
Lx_f = 16.092804675172488
Ly_f = -3.806928816522259
Lz_f = 0.008771463560693249
E_f = -1.46791290851501
period = -283.9439830646474
period_apo = -284.28920371275035
dt = -529.9999999999999
peri_apo_max_err = 0.1373300141075804
x_i = -13.947580337524414
y_i = -59.2327766418457
z_i = -84.4474868774414
v_x_i = 0.03033880516886711
v_y_i = 0.12821437418460846
v_z_i = -0.09591791778802872
ra = 209.3
dec = 26.8
distance = 46.559
pmra = -1.16
pmdec = -0.88
radial_velocity = 197.5
x = 1.588911738569831
y = 6.820493357600262
z = 45.042128965751324
v_x = -8.389029425525552
v_y = -34.865445651195984
v_z = 259.1064443270802
orbit_name = "mean"
idx_i = 76
t_i = -1021.162677088422
ra_err = 0.0
dec_err = 0.0
distance_err = 0.43080150822559915
pmra_err = 0.037
pmdec_err = 0.035
radial_velocity_err = 3.8
