pericentre = 4.4088052570234435
apocentre = 98.47514588646416
n_peris = 4
time_last_peri = -26.927210552027358
Lx_f = 10.801729956780406
Ly_f = -2.195691858219142
Lz_f = -0.024891381296522574
E_f = -1.521329405558977
period = -263.0581338544211
period_apo = -263.05813385442104
dt = -529.9999999999999
peri_apo_max_err = 0.30948793949343223
x_i = -4.494514465332031
y_i = -20.81199836730957
z_i = -96.14579772949219
v_x_i = 0.022141262888908386
v_y_i = 0.10806402564048767
v_z_i = -0.022795796394348145
ra = 209.3
dec = 26.8
distance = 46.0
pmra = -1.08
pmdec = -0.83
radial_velocity = 197.8
x = 1.4723202144064504
y = 6.738604661818598
z = 44.50159066183898
v_x = -1.8128434475959398
v_y = -11.803483019435049
v_z = 254.50447334662516
orbit_name = "smallperi"
idx_i = 219
t_i = -947.1128480703468
ra_err = 0.0
dec_err = 0.0
distance_err = 0.43080150822559915
pmra_err = 0.037
pmdec_err = 0.035
radial_velocity_err = 3.8
