break_radius_kpc = 1.1343494512309238
break_radius_arcmin = 84.80792382444216
r_h_i = 0.4443939568595761
r_h_f = 37.11391021182328
boundmass_i = 0.9999999999999999
boundmass_f = 0.34070008327985585
velocity_dispersion_f = 5.935264319267905
velocity_dispersion_i = 14.427248858369335
