pericentre = 10.47509164353161
apocentre = 105.15677547973793
pericentres = [10.971601442485557, 12.530432934554707, 9.373097329298217, 9.353987864277077, 10.20515726124213, 10.47509164353161, 10.474770562481124]
apocentres = [107.19157730592487, 105.94973196234513, 105.37682994751245, 105.28565939961949, 105.15677547973793, 105.05564493721792, 105.02927270028493]
period = 1.37525629679362
idx_peris = [17, 47, 76, 105, 134, 163, 192]
idx_apos = [32, 61, 90, 120, 149, 178, 207]
t_peris = [159.931640625, 460.126953125, 749.970703125, 1040.0732421875, 1329.9169921875, 1620.01953125, 1910.1220703125]
t_apos = [310.029296875, 599.873046875, 889.9755859375, 1189.912109375, 1480.0146484375, 1770.1171875, 2059.9609375]
idx_f = 166
idx_peri = 163
t_last_peri = 0.1415420898437505
t_f_gyr = 7.7799341796874995
ra_f = 207.273704519236
dec_f = 25.25140155226769
distance_f = 45.98162514841433
pmra_f = -1.247405521815732
pmdec_f = -0.9620025810428454
radial_velocity_f = -0.9620025810428454
theta0 = -103.57483354413702
chi2_best = 5.42332827352056
chi2_best_interp = 5.42332827352056
